### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by kN6jq** [webraybtl/CodeQLpy#1]
运行后提示/out/decode/lib 目录不存在，尝试过手动创建
![image](https://user-images.githubusercontent.com/27048404/211196849-4ec9b501-ece2-4c99-b6f1-0e8f349e26a0.png)

**Comment by webraybtl** [comment]
非常抱歉，这个错误是因为提交代码的时候不小心删除了decode目录。可以拉最新的代码，或者手动创建这个目录，空目录就行

**Comment by kN6jq** [comment]
代码的问题吧   
![image](https://user-images.githubusercontent.com/27048404/211230838-9617ca07-e171-4954-94b7-364439fbde1a.png)

会自动删除这个目录 我创建过了

**Comment by webraybtl** [comment]
如果没有jar包，确实会出现因为没有jar包导致的不生成Lib目录的bug，已经修复，未测试。
<img width="467" alt="image" src="https://user-images.githubusercontent.com/95903558/211238526-54df563f-d0be-4ca6-8e42-e34dda9fd888.png">
