### ISSUE TITLE
java堆设置的问题

### ISSUE THREAD

**Issue by murray-sky** [webraybtl/CodeQLpy#11]
在创建数据库的时候会出现堆内存设置过小，我去找这个codeql的堆内存设置的地方，但是没找到，师傅遇到过吗
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/80733736/213341106-181558a7-372e-4f29-8581-f634d78d4d88.png">

**Comment by webraybtl** [comment]
遇到过,目标源代码很大的时候会出现这种问题。在第一步结束之后会生成文件out/decode/run.sh文件，在文件开头增加代码export SEMMLE_JAVA_EXTRACTOR_JVM_ARGS='-Xmx4g -Xms512m'，这样可以设置codeql运行时默认的堆栈大小。
