### ISSUE TITLE
报错functions.py WARNING 

### ISSUE THREAD

**Issue by wawawa666** [webraybtl/CodeQLpy#14]
你好，我在大项目中使用，出现了如下问题
database.py INFO Found 2047 jsp files to decode
后面就一直 functions.py WARNING 
最终结果就是
 database.py WARNING Decode jsp file 0/2047 success 
 database.py ERROR Auto decompiler error, no java file found.
请问这个错误要怎么解决？

**Comment by murray-sky** [comment]
jsp编译有问题

**Comment by wawawa666** [comment]
已收到您的来信，我会尽快处理，祝您生活愉快！！！

**Comment by wawawa666** [comment]
> jsp编译有问题

放一个helloword这种示例文件进去能继续运行下去么？项目本身都能运行的

**Comment by webraybtl** [comment]
我猜测是因为你-t参数指定的源码路径不是网站根目录，你可以把运行时的截图发出来就更好了

**Comment by TaoLeonis** [comment]
![image](https://github.com/webraybtl/CodeQLpy/assets/26063300/e13ee2b0-9f3c-45cf-80e5-1470e8d3de00)
运行SpringMVC_demo出现相同报错

**Comment by wawawa666** [comment]
已收到您的来信，我会尽快处理，祝您生活愉快！！！

**Comment by hooray195** [comment]
解决了吗，怎么解决的

**Comment by wawawa666** [comment]
已收到您的来信，我会尽快处理，祝您生活愉快！！！
