### ISSUE TITLE
创建数据库提示java.io.EOFException: Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by murray-sky** [webraybtl/CodeQLpy#15]
当我创建数据库时，遇到了那种大型项目提示上面的报错
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/80733736/215316142-9d3bb559-fb49-486a-a6aa-97acf403886b.png">
我看到师傅你也去codeql官方那里反馈了，但是他说他解决不了，请问师傅后来是怎么解决的

**Comment by webraybtl** [comment]
这个问题我还在研究，后续会继续跟踪这个问题

**Comment by murray-sky** [comment]
> 这个问题我还在研究，后续会继续跟踪这个问题

👌

**Comment by murray-sky** [comment]
> 我似乎找到了这个问题的原因，如果对大型项目进行编译，直接拷贝WEB根目录是不行的，还要把全部的jar包拷贝进去，因为有的项目会引入WEB根目录以外的jar。你可以把项目所有的jar包都拷贝到WEB-INF/lib/目录，再试一下呢？

好的，我试试

**Comment by murray-sky** [comment]
还是不行，我感觉应该是源码过大了，我这反编译出来的源码有1.6G的大小，他也是提示在压缩的时候出问题了

**Comment by webraybtl** [comment]
这个问题可能还需要持久更新

**Comment by murray-sky** [comment]
好的，几天呢有点忙

**Comment by murray-sky** [comment]
我这边使用分步创建数据库的时候这个报错出现在最后一步
codeql database init --source-root <YourSourcePath> --language java <YourDBPath>
codeql database trace-command --working-dir=<YourSourcePath> <YourDBPath> <BuildCommand>
codeql database index-files --language properties --include-extension .properties --working-dir=<YourSourcePath> --exclude=target <YourDBPath>
codeql database index-files --language xml --include-extension .xml --working-dir=<YourSourcePath> --exclude=target <YourDBPath>
codeql database finalize <YourDBPath>
最后一步是去查web.xml的文件
