### ISSUE TITLE
这个超时问题是因为jdk版本吗？

### ISSUE THREAD

**Issue by Producer-CHN** [webraybtl/CodeQLpy#18]
timed out after 120 seconds
<img width="963" alt="image" src="https://user-images.githubusercontent.com/89628727/215400560-c01c5b79-9871-4a69-b0b0-10da5e08a00b.png">

**Comment by Producer-CHN** [comment]
指定jdk版本报错没有权限访问，已经是windows的管理员权限运行的了
<img width="901" alt="image" src="https://user-images.githubusercontent.com/89628727/215403344-2f2617bc-d819-446f-8fa3-f78bbf605361.png">

**Comment by Producer-CHN** [comment]
这里拼接不知道为什么多了个空格 是这个导致的吗，输入命令的时候没有多余的空格
<img width="954" alt="image" src="https://user-images.githubusercontent.com/89628727/215444414-8c18a7d8-986e-4adf-9d79-b1566d90b12d.png">

**Comment by webraybtl** [comment]
这个空格会有问题，我建议你去除目录中的空格

**Comment by Producer-CHN** [comment]
> 这个空格会有问题，我建议你去除目录中的空格

目录名称确实是没有空格的，不知道这个空格哪里来的

**Comment by webraybtl** [comment]
我明白了，不是这个空格的问题，这里本来就是两个参数。你可以看java -jar lib/jsp2class.jar -h 查看这个jar的说明。你不成功应该是其他原因

**Comment by muxueo** [comment]
师傅解决此问题了没，我手头碰到一个 和你一样。
但是目标是jdk7的，所以我也怀疑是不是Java版本问题？
