### ISSUE TITLE
jar包无法反编译的问题

### ISSUE THREAD

**Issue by murray-sky** [webraybtl/CodeQLpy#2]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/80733736/211517537-e7168a94-12a3-477a-99c2-fc2301b10605.png">
使用的是https://github.com/j3ers3/Hello-Java-Sec这个项目里面的jar包，无法反编译

**Comment by webraybtl** [comment]
我修复了SpringBoot项目中jar包引入异常导致的bug，并且针对javasec项目进行测试，相关结果在https://github.com/webraybtl/StudyCodeQLpy/tree/main/javasec_demo

**Comment by murray-sky** [comment]
> 我修复了SpringBoot项目中jar包引入异常导致的bug，并且针对javasec项目进行测试，相关结果在https://github.com/webraybtl/StudyCodeQLpy/tree/main/javasec_demo

好的，谢谢师傅了
