### ISSUE TITLE
javax.xml.stream.FactoryConfigurationError

### ISSUE THREAD

**Issue by Producer-CHN** [webraybtl/CodeQLpy#21]
大部分文件都是这个报错，最后无法生成数据库初始化
<img width="955" alt="image" src="https://user-images.githubusercontent.com/89628727/215476994-a0f8cf42-a9df-4b35-a9ec-f7336732c1d8.png">

**Comment by Producer-CHN** [comment]
最后初始化失败
<img width="955" alt="image" src="https://user-images.githubusercontent.com/89628727/215481872-35498331-86dd-4d25-a210-9a098b9932bb.png">

**Comment by webraybtl** [comment]
我目前看不出来是什么原因导致的，如果你能提供可复现的测试代码，我会对这种情况进行调试

**Comment by Producer-CHN** [comment]
> 我目前看不出来是什么原因导致的，如果你能提供可复现的测试代码，我会对这种情况进行调试

测试代码怎么给你，麻烦留个联系方式

**Comment by webraybtl** [comment]
> 

加我微信，ppdevxin
