### ISSUE TITLE
用ecj编译java文件的时候提示The import com.xxxx collides with another import statement

### ISSUE THREAD

**Issue by murray-sky** [webraybtl/CodeQLpy#22]
在eclipse的bug记录中有一条这种记录https://bugs.eclipse.org/bugs/show_bug.cgi?id=424839，这里就是两个类名相同，但是在不同的package中会导致编译错误，官方提供了https://git.eclipse.org/r/20293这个，但是已经访问不到了，师傅能解决一下吗

**Comment by webraybtl** [comment]
我本身就是使用的ecj，如果ecj本身有bug的话，我也只能等ecj更新
