### ISSUE TITLE
win无法使用？

### ISSUE THREAD

**Issue by gk0d** [webraybtl/CodeQLpy#24]
![image](https://user-images.githubusercontent.com/83335903/218315427-b736b27c-f6ef-472e-b65c-9f5a0c218626.png)
![image](https://user-images.githubusercontent.com/83335903/218315463-a6a84e86-4eec-4894-a9ed-7271831cb046.png)

![image](https://user-images.githubusercontent.com/83335903/218315113-7845e6b0-abd0-4c92-b7ae-267e4ed81bf8.png)
![image](https://user-images.githubusercontent.com/83335903/218315146-e6184dce-456f-4104-9dbb-7e72d1d96d2b.png)

**Comment by webraybtl** [comment]
你运行的时候报了什么错呢？

**Comment by gk0d** [comment]
没有任何信息提示，所以很疑惑

**Comment by webraybtl** [comment]
这大概是因为你的python3并没有加到环境变量，建议使用绝对路径来调用，eg: C:/python3/python.exe main.py -h

**Comment by gk0d** [comment]
非常感谢，使用绝对路径调用成功
