### ISSUE TITLE
Target SourceCode doesn't have WEB-INF/web.xml file,exit

### ISSUE THREAD

**Issue by wubantudl** [webraybtl/CodeQLpy#25]
2023/02/16 12:44:02 database.py ERROR Target SourceCode doesn't have WEB-INF/web.xml file,exit

**Comment by wubantudl** [comment]
麻烦大哥抽空解决一下，辛苦啦

**Comment by murray-sky** [comment]
从其他项目中复制一份web.xml放到WEB-INF/web.xml 里面

**Comment by webraybtl** [comment]
验证这个是为了代码规范，约束传递了网站根目录，如果项目是在没有这个，可以随便从其他项目拷贝一个WEB-INF/web.xml
