### ISSUE TITLE
师傅你好，mac 兼容吗

### ISSUE THREAD

**Issue by jielansudo** [webraybtl/CodeQLpy#28]
看到很多关于windows得bug修复，不知道Mac能否正常兼容

**Comment by jielansudo** [comment]
想请教一下，只能单个jar进行创建数据库吗，可以文件夹下所有的jar吗

**Comment by webraybtl** [comment]
mac可以使用的，单个jar包只是考虑SpringBoot的场景，多个jar包应该是一个正常的WEB项目，按照文件夹的方式来创建数据库就行了
