### ISSUE TITLE
qlpath 问题

### ISSUE THREAD

**Issue by Iceqaq** [webraybtl/CodeQLpy#3]
qlpath是什么路径呢？是指存放了codeql.exe  的目录吗？

**Comment by webraybtl** [comment]
不是，是指codeql sdk中测试ql文件地址，一般是ql/java/ql/test/这个目录。这个目录下面需要有一个qlpack.yml文件。

**Comment by Iceqaq** [comment]
> 不是，是指codeql sdk中测试ql文件地址，一般是ql/java/ql/test/这个目录。这个目录下面需要有一个qlpack.yml文件。

3q
