### ISSUE TITLE
springboot的jar包支持jar包内部的jar进行扫描

### ISSUE THREAD

**Issue by murray-sky** [webraybtl/CodeQLpy#31]
像ruoyi这种打包好的jar包，lib下面还是有jar包是网站代码

**Comment by webraybtl** [comment]
师傅什么意思？有没有demo可以分享给我试一下？

**Comment by murray-sky** [comment]
就比如若依来说把ruoyi-admin
ruoyi-common
ruoyi-framework
ruoyi-generator
ruoyi-quartz
ruoyi-system
这几个模块编译成jar包，最后在把这些jar+加上springboot那些依赖一起编译到一个jar中，希望在反编译jar包的时候能够指定反编译jar包中的的部分jar包

**Comment by webraybtl** [comment]
很好的建议，会进行相应优化

**Comment by webraybtl** [comment]
代码已经更新，Springboot环境下新增-j参数，用于指定要编译的内部jar包

**Comment by murray-sky** [comment]
能反编译了，但是在BOOT-INF.classes下面的class文件反编译后包不正确，没有将包名转化为目录，而且与jar包里面反编译出来的源码没合并

**Comment by webraybtl** [comment]
包名不正确是属于bug，已修复。源码没有合并是故意如此的，这个不影响后续执行

**Comment by murray-sky** [comment]
可以了
