### ISSUE TITLE
这种目录结构如何运行？

### ISSUE THREAD

**Issue by helloyw** [webraybtl/CodeQLpy#43]
师傅求教一下
<img width="775" alt="image" src="https://github.com/webraybtl/CodeQLpy/assets/32027872/746f3f35-f601-487d-a0a7-d729aefae457">

WEB-INF/lib为jar包，关键代码都在jar里面，jsp文件只有几个，没啥用主要文件都在几个lib文件夹的jar里，我该怎么执行命令呢？
python main.py -t C:\Users\john\Desktop\oa\ -c -j oa-*?.jar 失败了
错误信息：
`2023/09/25 17:02:43 database.py WARNING Decode jsp file 0/11 success

2023/09/25 17:02:43 database.py ERROR Auto decompiler error, no java file found.
`

**Comment by pang0lin** [comment]
python main.py -t C:\Users\john\Desktop\oa\ -c -j oa.*?\.jar  命令改成这样试一下呢？后面的jar是按照正则来的，-在正则中是有意义的，不能直接使用
