### ISSUE TITLE
文件名、目录名或卷标语法不正确。

### ISSUE THREAD

**Issue by Iceqaq** [webraybtl/CodeQLpy#5]
如图所示
![image](https://user-images.githubusercontent.com/43596990/212826383-99b1ca7d-1829-4396-97b1-104d6c6f324e.png)

pei配置如下
![image](https://user-images.githubusercontent.com/43596990/212826439-0f9e36f3-abb5-47b6-88b6-eff6d7329981.png)

目录如下，跟着配置不知道哪里有些问题，望指教
![image](https://user-images.githubusercontent.com/43596990/212826524-896db771-7b99-4e18-85b8-e156d7c69bcc.png)

**Comment by webraybtl** [comment]
<img width="823" alt="image" src="https://user-images.githubusercontent.com/95903558/212830011-48f2aa9d-efdb-47b9-8068-84f1cedf3a70.png">
这里没有双引号
