### ISSUE TITLE
运行codeql --version时出现的Bug

### ISSUE THREAD

**Issue by Iceqaq** [webraybtl/CodeQLpy#7]
如下图所示
![image](https://user-images.githubusercontent.com/43596990/213106678-ed9598e1-30f7-43ff-9643-d6e96f2d498e.png)

本地确认codeql  version在系统环境变量之下

**Comment by webraybtl** [comment]
我无法复现你出现的这个报错，或许你可以尝试把print(e)改成traceback.print_exc() 打印详细的错误信息。
